### ISSUE TITLE
For --dir option, either create dir or check early

### ISSUE THREAD

**Issue by martinsvalin** [henrik/sipper#10]
Running with `--dir /path/to/nowhere`, Sipper first downloads the feed and then dies with `(File.Error) could not list directory`.

I see two options. Either create the directory (which might be bad if the error is due to a typo). Or check the inputs early, and report a friendly error.

(I'll be happy to PR whatever option you'd like to go with, if you're busy.)

**Comment by henrik** [comment]
Thanks so much for the report!

It's documented as automatically creating the dir if it doesn't exist – that's the behaviour I aimed for.

I'm not too busy really, but if you want to have a go at it, it would be fun to get more contributors :)

**Comment by henrik** [comment]
As you might have noticed, test coverage in this project isn't high. If you do contribute this, tests would be great but not an absolute must, if it's tricky and you feel confident after manually checking it.

**Comment by henrik** [comment]
Fixed this myself (in af0758ed8a51cd46a79ba7cf7b99fb7620841e0d) since it's a bug. Hope that's not a problem for you, Martin!
