### ISSUE TITLE
Add option like `--batch` or `--after`

### ISSUE THREAD

**Issue by martinsvalin** [henrik/sipper#11]
When running sipper twice with --max 3, I hoped I'd get six episodes, but ended up re-downloading the same three.

I realize my expectations may not match everyones, but I think it'd be useful to download episodes in increments if I so choose. If I use the same download directory, a simple dir listing could filter out episodes. Another option would be an --offset option, but those aren't very userfriendly. If I were to add options, I think I'd prefer something along the lines of `--after 37` or `--after 195`, with episode numbers.

Again, I'll be happy to have a look if you think these are features you'd like to support in Sipper.

**Comment by henrik** [comment]
My single use case for `--max` was during initial development, to do less work while I was figuring stuff out.

At this point, I don't use any limiting myself, but I'm open for anything others find useful :) PRs would be awesome.

I agree `--offset` seems a bit low-level. If you would find batched downloads useful, maybe an option like `--batch 5` could be worthwhile. We could probably then remove `--max` and see if anyone complains.

`--after 37` also sounds reasonable.

Again, I don't personally have these use cases, but if you do, or you think they would be fun to code and they don't complicate things a ton, go for it :D

**Comment by henrik** [comment]
@martinsvalin Still want to do this one? If not I might close it or see if anyone else is interested in implementing it.

**Comment by martinsvalin** [comment]
Sorry, go ahead. If I somehow find myself some time to fix this, I'll just PR out of the blue instead, but I'm not counting on it.

**Comment by henrik** [comment]
@martinsvalin No worries. Will close this for now then.
