### ISSUE TITLE
Download Sips in order, from the beginning 

### ISSUE THREAD

**Issue by zeroum** [henrik/sipper#14]
Hello! I'm just beginning in Elixir, and I'm starting to watch the Sips in orders, as I believe out they're for real beginners at the first episodes.

Is there an option to download them in order, from the beginning, instead of going all the other way around? There are over 200 episodes right now.

**Comment by henrik** [comment]
Hey,

There isn't but I'm happy to add it. Do you want to take a shot at it first? Only if you want to :)

**Comment by zeroum** [comment]
It might be a bit of a chicken and egg problem, but, yeah, sure!

**Comment by henrik** [comment]
@zeroum Haha :D Give it a shot. Let me know if you need any assistance. And if you change your mind, let me know and I can add the functionality :)

**Comment by sunu** [comment]
The `--oldest-first` flag makes it possible to download epsodes in reverse order, doesn't it?

**Comment by henrik** [comment]
Oh yes, this is now done. Good catch, @sunu!
