### ISSUE TITLE
(MatchError) no match of right hand side value: %HTTPotion.Response...

### ISSUE THREAD

**Issue by hipertracker** [henrik/sipper#19]
$ ./sipper --user mylogin  --pw mypassword

```⠙ Getting feed…*\* (MatchError) no match of right hand side value: %HTTPotion.Response{body: "", headers: ["Cache-Control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0", Connection: "close", "Content-Length": "0", "Content-Type": "text/html", Date: "Fri, 12 Feb 2016 01:44:15 GMT", Expires: "Thu, 19 Nov 1981 08:52:00 GMT", P3P: "CP=\"NOI CURa OUR NOR UNI\"", Pragma: "no-cache", Server: "Apache", "Set-Cookie": "symfony=su86j0fhh4e2kpktcl6tonb1k1; path=/; HttpOnly", Vary: "Accept-Encoding,User-Agent", "WWW-Authenticate": "Basic realm=\"Elixir Sips\""], status_code: 401}
    (sipper) lib/sipper/dpd_cart_client.ex:11: Sipper.DpdCartClient.get_feed/1
    (sipper) lib/sipper/feed_downloader.ex:9: anonymous fn/1 in Sipper.FeedDownloader.run/1
    lib/progress_bar/spinner.ex:28: ProgressBar.Spinner.render/2
    (sipper) lib/sipper/runner.ex:3: Sipper.Runner.run/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2

```
```

**Comment by henrik** [comment]
Thanks for the error report.

Status 401 means unauthorised – wrong username or password.

Has it worked for you before and then stopped working? Did you provide your real auth details per the docs?

Would be nice to show that error message more clearly. If you want to, have a stab at that yourself and make a pull request :) Only if you want to.

**Comment by hipertracker** [comment]
It worked fine before. It stopped to work later. It's not wrong login nor password because I am able to log in to my user account using the same data. I tested it few times.

 But.. I have tested it again today and it all works fine again. I guess it had to be a temporary problem.
