### ISSUE TITLE
Not able to download any video.

### ISSUE THREAD

**Issue by collegeimprovements** [henrik/sipper#20]
I ran `./sipper --user me@example.com --pw mypassword` command. I believe this will download every video. I'm getting this error each time.

``` elixir
⠦ Getting feed…** (HTTPotion.HTTPError) req_timedout
    (httpotion) lib/httpotion.ex:209: HTTPotion.handle_response/1
    (sipper) lib/sipper/dpd_cart_client.ex:10: Sipper.DpdCartClient.get_feed/1
    (sipper) lib/sipper/feed_downloader.ex:9: anonymous fn/1 in Sipper.FeedDownloader.run/1
    lib/progress_bar/spinner.ex:28: ProgressBar.Spinner.render/2
    (sipper) lib/sipper/runner.ex:3: Sipper.Runner.run/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by henrik** [comment]
Thanks for the error report!

Yeah, it should download all of them. I'm afraid I don't have an active subscription currently, but maybe I could ask @kpanic who contributed a feature recently (even related to timeouts) – does Sipper still work for you?

**Comment by kpanic** [comment]
Yes @henrik for me it's enough to set in `config/config.exs`
`feed_timeout_ms: 50_000`

and regenerate the sipper ebuild.script

**Comment by kpanic** [comment]
Try to increase the timeout @collegeimprovements

**Comment by henrik** [comment]
@kpanic Thank you for checking :)

**Comment by collegeimprovements** [comment]
The same error persists :( I tried `50_000` and `5_00_000` both as the values of `feed_timeout_ms`.

**Comment by henrik** [comment]
@collegeimprovements Did the problem go away? I saw a reply from you in an email notification that it still wasn't working, but I don't see it on the web, so maybe you removed it.

Otherwise, one important point is that you need to recompile (by running `mix`) after changing the config.exs file. I just added a comment to that effect, and I also bumped the default from 15 to 100 seconds.

**Comment by collegeimprovements** [comment]
Sorry, after making the change it worked. Thanks a lot @henrik & @kpanic. It is working charmingly and I'm able to download all the required material. Kudos. Sorry for the late reply.

**Comment by henrik** [comment]
@collegeimprovements Oh, happy to hear it! :)
