### ISSUE TITLE
warning: Float.to_string/2 is deprecated, use :erlang.float_to_binary/2 instead

### ISSUE THREAD

**Issue by peterwillcn** [henrik/sipper#25]
███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   5% (20.97/427.44 MB)warning: Float.to_string/2 is deprecated, use :erlang.float_to_binary/2 instead
  (elixir) lib/float.ex:414: Float.to_string/2
  lib/progress_bar/bytes.ex:10: ProgressBar.Bytes.format/2
  lib/progress_bar/determinate.ex:47: ProgressBar.Determinate.bytes/3
  lib/progress_bar/determinate.ex:23: ProgressBar.Determinate.render/3
  (sipper) lib/sipper/dpd_cart_client.ex:56: Sipper.DpdCartClient.receive_file/1

**Comment by henrik** [comment]
Thank you! I've updated `progress_bar` to use `:erlang.float_to_binary` instead, and I've updated Sipper to use that one. Please let me know if it resolves the problem for you.

**Comment by peterwillcn** [comment]
This problem has been fixed, Thank you! 
Have a great day! @henrik

**Comment by henrik** [comment]
@peterwillcn Awesome, thanks for telling me. You as well!
